export const IMPORT_EXAMPLE = {
  schemaVersion: 1,
  manifest: {
    id: 'my-pack-demo',
    title: '二次函数练习',
    version: '1.0.0',
    subject: 'math',
    description: '原创练习',
    changelog: '初版',
    compatibility: 'Review 1.x',
  },
  knowledge: [
    {
      id: 'my-quadratic',
      subject: 'math',
      course: '数学',
      unit: '函数',
      chapter: '二次函数',
      title: '二次函数顶点',
      description: '利用配方理解顶点式。',
      prerequisites: [],
      relatedNodes: [],
      importance: 0.8,
      examWeight: 0.8,
      skills: [{ id: 'vertex', title: '求顶点', difficulty: 2 }],
      source: '外部 AI 原创',
      version: '1.0.0',
    },
  ],
  questions: [
    {
      schemaVersion: 1,
      id: 'my-quadratic-001',
      nodeId: 'my-quadratic',
      skillId: 'vertex',
      subject: 'math',
      type: 'choice',
      prompt: '函数 $y=(x-2)^2+3$ 的顶点是什么？',
      answer: '$(2,3)$',
      options: ['$(2,3)$', '$(-2,3)$', '$(2,-3)$', '$(-2,-3)$'],
      explanation: '顶点式 $y=(x-h)^2+k$ 的顶点是 $(h,k)$。',
      difficulty: 2,
      expectedSeconds: 30,
      variant: 'vertex-form',
      solution: [
        '已知顶点式。',
        '比较标准形式。',
        '$h=2, k=3$。',
        '检验代入 $x=2$ 得 $y=3$。',
        '顶点为 $(2,3)$。',
      ],
      source: '外部 AI 原创',
      tags: ['函数'],
      version: '1.0.0',
    },
  ],
};
