import {
  SUBJECTS,
  type Subject,
  type Node,
  type Question,
  type Pack,
} from './model';
// This starter pack is reference content. Personal mastery always starts unassessed.
const content: [Subject, string, string, string, string[]][] = [
  [
    'chinese',
    '字词',
    '易错字词',
    '沮丧（jǔ sàng）：灰心失望。狼藉（láng jí）：乱七八糟、杂乱不堪。蹒跚（pán shān）：腿脚不灵便、走路缓慢摇摆的样子。',
    ['字形记忆', '词义理解', '语境运用'],
  ],
  [
    'chinese',
    '字词',
    '成语辨析',
    '“首当其冲”指最先受到攻击或遭遇灾难；“首屈一指”指位居第一、最好。辨析时应结合语境与感情色彩。',
    ['词义理解', '辨析', '语境运用'],
  ],
  [
    'chinese',
    '古诗文',
    '春望',
    '杜甫，唐代。《春望》：国破山河在，城春草木深。感时花溅泪，恨别鸟惊心。烽火连三月，家书抵万金。白头搔更短，浑欲不胜簪。表达忧国伤时、思家悲己之情。',
    ['内容记忆', '名句理解', '作者背景', '主旨分析'],
  ],
  [
    'chinese',
    '古诗文',
    '论语 · 学而时习之',
    '“学而时习之，不亦说乎？”意思是学习了知识，按时温习，不也是令人喜悦的事吗？“说”同“悦”，愉快。',
    ['文言解释', '通假字', '文言翻译'],
  ],
  [
    'chinese',
    '阅读理解',
    '小说的环境描写',
    '分析环境描写应联系文本：交代时间地点，渲染氛围，烘托人物心情，推动情节，暗示主题。并非每段环境描写都包含所有作用。',
    ['识别', '作用分析', '文本证据'],
  ],
  [
    'chinese',
    '阅读理解',
    '说明方法',
    '常见说明方法包括举例子、列数字、作比较、打比方、分类别。答题需说明具体方法、说明对象特征及表达效果。',
    ['识别', '作用分析'],
  ],
  [
    'chinese',
    '阅读理解',
    '议论文论证',
    '论点是作者的主张；论据用来支持论点；论证说明论据如何支持论点。分析不能只摘录论据而忽略推理关系。',
    ['概念理解', '论证分析'],
  ],
  [
    'math',
    '代数基础',
    '一元一次方程',
    '通过等式两边进行相同的合法运算保持等式成立，逐步求出未知数；代入原方程检验。',
    ['概念理解', '计算', '实际应用'],
  ],
  [
    'math',
    '函数',
    '二次函数',
    '二次函数 y=ax²+bx+c（a≠0）的顶点横坐标为 −b/(2a)。配方为 y=a(x−h)²+k，顶点为(h,k)。a>0 时有最小值k。',
    ['概念理解', '图像识别', '求顶点', '最值', '实际应用'],
  ],
  [
    'math',
    '几何',
    '三角形与勾股定理',
    '直角三角形两直角边a、b与斜边c满足a²+b²=c²。使用前必须确认直角与斜边的位置。',
    ['概念理解', '计算', '证明', '实际应用'],
  ],
  [
    'math',
    '几何',
    '相似三角形',
    '对应角相等、对应边成比例的两个三角形相似。相似比为k时，对应周长比为k，面积比为k²。',
    ['概念理解', '图形识别', '证明'],
  ],
  [
    'math',
    '统计',
    '平均数与中位数',
    '平均数为总和除以数量；中位数是数据从小到大排序后的中间值。数据个数为偶数时取中间两数的平均数。',
    ['概念理解', '数据分析'],
  ],
  [
    'english',
    'Keyterms',
    'Suspense',
    'Suspense is the reader’s feeling of uncertainty and anticipation about what will happen. Delayed information, foreshadowing, pacing and threatened outcomes can create suspense.',
    ['Definition', 'Identification', 'Technique', 'Analysis', 'Application'],
  ],
  [
    'english',
    'Keyterms',
    'Foreshadowing',
    'Foreshadowing is a clue that hints at a later event. It prepares readers for developments without fully revealing them. It differs from a flashback, which presents an earlier event.',
    ['Definition', 'Identification', 'Comparison', 'Analysis'],
  ],
  [
    'english',
    'Keyterms',
    'Symbolism',
    'Symbolism uses a concrete object, action or image to suggest an abstract meaning beyond its literal role. A symbol’s meaning depends on its textual context.',
    ['Definition', 'Identification', 'Analysis'],
  ],
  [
    'english',
    'Keyterms',
    'Imagery',
    'Imagery is descriptive language that evokes sensory experience: sight, sound, smell, taste or touch. Analyze which senses it engages and how it shapes tone or meaning.',
    ['Definition', 'Identification', 'Analysis'],
  ],
  [
    'english',
    'Keyterms',
    'Irony',
    'Verbal irony contrasts intended and literal meaning; situational irony contrasts expectation and outcome; dramatic irony arises when the audience knows more than a character.',
    ['Definition', 'Comparison', 'Identification'],
  ],
  [
    'english',
    'Keyterms',
    'Romanticism & Gothic',
    'Romantic literature often values imagination, emotion and nature. Gothic literature commonly uses disturbing settings, mystery and dread; it overlaps with but is not identical to Romanticism.',
    ['Definition', 'Characteristics', 'Comparison'],
  ],
  [
    'english',
    'Writing',
    'Analytical Writing',
    'A strong analytical paragraph states a defensible claim, selects relevant evidence, explains how the evidence supports the claim, and links the analysis to the larger argument.',
    [
      'Thesis',
      'Evidence',
      'Analysis',
      'Organization',
      'Clarity',
      'Language',
      'Grammar',
    ],
  ],
  [
    'ce',
    'Grammar',
    'Subject–verb agreement',
    'The verb agrees in number with the subject, not with a noun in an intervening prepositional phrase. “The collection of essays is useful.”',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Verb tense',
    'Use tense consistently to express the intended sequence of events. Past perfect describes an event completed before another past event.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Pronouns',
    'Pronouns need clear antecedents and agreement in number. Choose subjective, objective or possessive forms according to the pronoun’s grammatical role.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Modifiers',
    'A modifier should clearly describe the intended word. An introductory participial phrase should modify the subject that immediately follows it.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Parallel structure',
    'Items of equal grammatical importance should use matching structures, such as “reading, writing, and revising.”',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Punctuation',
    'A semicolon can join two closely related independent clauses. A colon introducing an explanation or list normally follows a complete independent clause.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Sentence boundaries',
    'Two independent clauses cannot be joined by a comma alone. Use a period, semicolon, or comma with a coordinating conjunction when appropriate.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Clauses',
    'An independent clause expresses a complete thought. A dependent clause contains a subject and verb but depends on a main clause for a complete sentence.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Transitions',
    'Choose a transition that matches the logical relationship: contrast, continuation, example, cause or result. “However” marks contrast; “therefore” marks a result.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'Grammar',
    'Word choice',
    'Precise word choice must fit the meaning, register and context of the passage. A familiar synonym may not preserve the author’s intended meaning.',
    ['Identification', 'Application'],
  ],
  [
    'ce',
    'SAT / ACT',
    'Rhetorical synthesis',
    'Read the writing goal first. Select and combine only the notes that support that goal; exclude irrelevant details even when they are factually correct.',
    ['Identification', 'Application'],
  ],
  [
    'physics',
    '机械运动',
    '运动与速度',
    '判断运动需要选定参照物。匀速直线运动速度v=s/t；速度单位换算：1 m/s=3.6 km/h。',
    ['概念理解', '计算', '图像分析'],
  ],
  [
    'physics',
    '声现象',
    '声音的产生与传播',
    '声音由物体振动产生，传播需要介质，真空不能传声。音调与频率有关，响度与振幅和距离等因素有关。',
    ['概念理解', '现象解释'],
  ],
  [
    'physics',
    '物态变化',
    '熔化与汽化',
    '熔化是固态变为液态，汽化是液态变为气态，二者都吸热。晶体在熔化过程中持续吸热而温度保持不变。',
    ['概念理解', '实验分析'],
  ],
  [
    'physics',
    '光现象',
    '光的反射',
    '反射光线、入射光线与法线在同一平面内；反射光线和入射光线分居法线两侧；反射角等于入射角。角度均相对于法线测量。',
    ['概念理解', '作图', '现象解释'],
  ],
  [
    'physics',
    '透镜',
    '凸透镜成像',
    '当物距大于2倍焦距时，凸透镜成倒立、缩小的实像；当物距在1倍与2倍焦距之间时，成倒立、放大的实像。',
    ['概念理解', '光路分析', '实验分析'],
  ],
  [
    'physics',
    '质量与密度',
    '密度与测量',
    '密度ρ=m/V，单位可用kg/m³或g/cm³。测量液体密度可用天平测质量、量筒测体积，注意量筒读数时视线与凹液面底部相平。',
    ['概念理解', '计算', '仪器读数', '误差分析'],
  ],
  [
    'physics',
    '力',
    '力的作用效果',
    '力可以改变物体的运动状态，也可以改变物体的形状。力的大小、方向和作用点称为力的三要素。',
    ['概念理解', '受力分析'],
  ],
  [
    'physics',
    '运动与力',
    '惯性与二力平衡',
    '惯性是物体保持原来运动状态不变的性质。二力平衡需要两力作用在同一物体上，大小相等、方向相反、在同一直线上。',
    ['概念理解', '现象解释'],
  ],
  [
    'physics',
    '压强',
    '压强与液体压强',
    '固体压强p=F/S；静止液体内部压强p=ρgh，与液体密度和深度有关。同种液体同一深度处各方向压强相等。',
    ['概念理解', '计算', '实验分析'],
  ],
  [
    'physics',
    '浮力',
    '阿基米德原理',
    '浸在液体中的物体所受浮力等于它排开的液体所受重力：F浮=ρ液gV排。漂浮时浮力等于重力。',
    ['概念理解', '计算', '实验分析'],
  ],
  [
    'physics',
    '功',
    '功与功率',
    '功W=Fs，其中s是物体在力的方向上移动的距离；功率P=W/t表示做功快慢。',
    ['概念理解', '计算'],
  ],
  [
    'physics',
    '机械能',
    '动能与势能',
    '动能与质量和速度有关；重力势能与质量和高度有关。忽略摩擦等阻力时，动能与势能可相互转化，机械能总量保持不变。',
    ['概念理解', '实验分析', '现象解释'],
  ],
  [
    'chemistry',
    '物质与变化',
    '物质性质与变化',
    '物理变化没有生成其他物质，化学变化生成了其他物质。判断依据是是否生成新物质，而不能仅凭发光、发热或颜色变化。',
    ['概念理解', '变化判断'],
  ],
  [
    'chemistry',
    '空气与氧气',
    '空气与氧气',
    '空气按体积分数约含78%氮气、21%氧气。氧气能支持燃烧，但氧气本身通常不作燃料。',
    ['概念理解', '实验现象'],
  ],
  [
    'chemistry',
    '微观结构',
    '分子、原子与元素',
    '原子是化学变化中的最小粒子。元素是质子数相同的一类原子的总称。分子是保持由分子构成的物质化学性质的最小粒子。',
    ['概念理解', '比较辨析'],
  ],
  [
    'chemistry',
    '水',
    '水的组成',
    '电解水时，正极产生氧气、负极产生氢气，气体体积比约1:2。水由氢、氧两种元素组成。',
    ['概念理解', '实验分析'],
  ],
  [
    'chemistry',
    '化学用语',
    '化学式与化合价',
    '化合物中各元素正负化合价的代数和为零。化学式中的下标表示原子个数比，不能在配平方程式时随意改变。',
    ['化学式', '化合价', '计算'],
  ],
  [
    'chemistry',
    '化学方程式',
    '质量守恒与配平',
    '化学反应前后元素种类和各元素原子数不变。配平应调整化学式前的系数，使各元素原子数相等，并检查反应条件。',
    ['方程式回忆', '配平', '反应条件'],
  ],
  [
    'chemistry',
    '燃烧',
    '燃烧条件',
    '燃烧通常需要可燃物、氧气（或空气）、温度达到着火点。灭火可以移除可燃物、隔绝氧气或降温至着火点以下。',
    ['概念理解', '实验分析'],
  ],
  [
    'chemistry',
    '碳及其化合物',
    '碳与二氧化碳',
    '碳充分燃烧生成二氧化碳；二氧化碳能使澄清石灰水变浑浊。二氧化碳通常既不燃烧，也不支持燃烧。',
    ['反应条件', '实验现象', '方程式回忆'],
  ],
  [
    'history',
    '近代世界',
    '工业革命',
    '工业革命首先从18世纪60年代的英国兴起，以机器生产逐步代替手工劳动。它提高了生产力，促进工厂制度和城市化，也加剧了环境污染和社会矛盾。',
    ['时间事件', '原因', '过程', '影响', '史料分析'],
  ],
  [
    'history',
    '近代世界',
    '新航路的开辟',
    '15至16世纪的远洋航行加强了世界各地区的联系，促进贸易发展，也伴随殖民扩张和掠夺。评价应兼顾不同地区与群体。',
    ['时间事件', '人物事件', '原因', '影响', '比较'],
  ],
  [
    'history',
    '中国近代史',
    '洋务运动',
    '19世纪60至90年代，洋务派以“自强”“求富”为口号，创办近代军事、民用工业等事业。它推动中国近代化起步，但未从根本上改变封建制度。',
    ['时间事件', '人物事件', '过程', '结果', '意义'],
  ],
  [
    'history',
    '历史方法',
    '史料分析',
    '分析史料应先判断作者、时间、背景和立场，区分事实与评价，再结合所学与其他证据，说明史料能支持的结论及局限。',
    ['来源识别', '证据评价', '论证'],
  ],
  [
    'biology',
    '细胞与生命活动',
    '细胞的结构与功能',
    '细胞是生物体结构和功能的基本单位。比较动物细胞和植物细胞，理解细胞膜、细胞质、细胞核、线粒体、叶绿体和液泡的作用。',
    ['结构识别', '功能理解', '比较分析'],
  ],
  [
    'biology',
    '植物的生活',
    '光合作用与呼吸作用',
    '分析光合作用和呼吸作用的条件、场所、原料、产物以及物质和能量变化。区分两种过程，解释相关实验。',
    ['概念理解', '过程分析', '实验分析'],
  ],
  [
    'biology',
    '人体生理',
    '消化与吸收',
    '理解消化系统的组成，区分物理性消化和化学性消化，分析小肠适于吸收的结构特点。',
    ['结构识别', '功能理解', '实验分析'],
  ],
  [
    'biology',
    '人体生理',
    '呼吸与循环',
    '理解肺泡和组织细胞处的气体交换，分析心脏结构、血液循环途径及其与物质运输的关系。',
    ['结构识别', '过程分析', '实际应用'],
  ],
  [
    'biology',
    '遗传与进化',
    '遗传与变异',
    '理解性状、基因、DNA和染色体的关系，区分可遗传变异与不可遗传变异，通过实例解释自然选择。',
    ['概念理解', '关系分析', '实际应用'],
  ],
  [
    'biology',
    '生物与环境',
    '生态系统',
    '分析生态系统的组成、食物链与食物网，解释能量流动、物质循环以及生态系统的调节能力。',
    ['概念理解', '关系分析', '证据解释'],
  ],
];
export const seedNodes: Node[] = content.map(
  ([subject, chapter, title, description, skills], i) => ({
    id: `core-${subject}-${content.slice(0, i).filter((x) => x[0] === subject).length + 1}`,
    subject,
    course: SUBJECTS.find((s) => s.id === subject)!.course,
    unit: chapter,
    chapter,
    title,
    description,
    prerequisites: [],
    relatedNodes: [],
    importance: 0.75,
    examWeight: 0.8,
    skills: skills.map((title, i) => ({
      id: `skill-${i + 1}`,
      title,
      difficulty: i ? 2 : 1,
    })),
    source: 'Review 基础学习包 · 原创整理',
    version: '1.0.0',
  }),
);
seedNodes.find((n) => n.id === 'core-math-2')!.prerequisites = ['core-math-1'];
seedNodes.find((n) => n.id === 'core-physics-10')!.prerequisites = [
  'core-physics-6',
  'core-physics-9',
];
seedNodes.find((n) => n.id === 'core-chemistry-6')!.prerequisites = [
  'core-chemistry-3',
  'core-chemistry-5',
];
export const seedQuestions: Question[] = seedNodes.flatMap((n) => [
  {
    schemaVersion: 1 as const,
    id: `${n.id}-concept`,
    nodeId: n.id,
    skillId: n.skills[0].id,
    subject: n.subject,
    type: 'recall',
    prompt:
      n.subject === 'english' || n.subject === 'ce'
        ? `Explain ${n.title} in your own words. What is one important feature?`
        : `回忆「${n.title}」的核心内容，并说出一个容易混淆的地方。`,
    answer: n.description,
    explanation:
      '先独立回忆，再对照要点。若只能辨认而无法主动想起，请选择“不确定”。',
    difficulty: 1,
    expectedSeconds: 25,
    variant: 'definition',
    source: n.source,
    tags: [n.chapter, '基础'],
    version: '1.0.0',
  },
  {
    schemaVersion: 1 as const,
    id: `${n.id}-analysis`,
    nodeId: n.id,
    skillId: n.skills.at(-1)!.id,
    subject: n.subject,
    type: 'subjective',
    prompt:
      n.subject === 'english' || n.subject === 'ce'
        ? `Explain how you would apply ${n.title}. Give an original example and explain why it illustrates the concept.`
        : `请解释「${n.title}」的核心规律或观点，并结合一个具体例子说明。`,
    answer: n.description,
    explanation: '清楚表述概念、提供例子、说明两者联系。',
    difficulty: 3,
    expectedSeconds: 100,
    variant: 'application',
    source: n.source,
    tags: [n.chapter, '表达'],
    version: '1.0.0',
    rubric: [
      {
        id: 'concept',
        title: '概念准确',
        max: 2,
        description: '符合参考知识，没有实质性概念错误。',
        skillId: n.skills.at(-1)!.id,
      },
      {
        id: 'example',
        title: '证据与例子',
        max: 2,
        description: '提供具体且相关的例子。',
        skillId: n.skills.at(-1)!.id,
      },
      {
        id: 'analysis',
        title: '分析与联系',
        max: 2,
        description: '说明例子如何体现概念，表达清晰。',
        skillId: n.skills.at(-1)!.id,
      },
    ],
  },
]);
function add(
  nodeId: string,
  skill: number,
  prompt: string,
  answer: string,
  explanation: string,
  extra: Partial<Question> = {},
) {
  const n = seedNodes.find((x) => x.id === nodeId)!;
  seedQuestions.push({
    schemaVersion: 1,
    id: `${nodeId}-q${seedQuestions.filter((q) => q.nodeId === nodeId).length + 1}`,
    nodeId,
    skillId: n.skills[skill - 1].id,
    subject: n.subject,
    type: 'recall',
    prompt,
    answer,
    explanation,
    difficulty: 2,
    expectedSeconds: 35,
    variant: 'specific-example',
    source: n.source,
    tags: [n.chapter],
    version: '1.0.0',
    ...extra,
  });
}
add(
  'core-chinese-1',
  1,
  '根据拼音，在心中写出汉字：\njǔ sàng　　láng jí　　pán shān',
  '沮丧　狼藉　蹒跚',
  '注意“沮”的三点水、“藉”的草字头，以及“蹒跚”的足字旁。',
);
add(
  'core-chinese-1',
  3,
  '“走过泥泞的小路，祖父的脚步有些____。”\n选择：狼藉 / 蹒跚 / 沮丧',
  '蹒跚',
  '“蹒跚”形容走路缓慢摇摆。狼藉形容杂乱，沮丧形容心情。',
);
add(
  'core-chinese-2',
  2,
  '“他在比赛中拿到了第一名，可谓首当其冲。”这句话中的成语用得恰当吗？',
  '不恰当。可改用“首屈一指”或直接说“名列第一”。',
  '“首当其冲”不是“第一个”，而是最先受到攻击或遭遇灾难。',
);
add(
  'core-chinese-3',
  1,
  '回忆《春望》：\n烽火连三月，________。',
  '家书抵万金。',
  '战乱中音讯难通，家信格外珍贵。',
  { variant: 'poem-next' },
);
add(
  'core-chinese-3',
  1,
  '回忆上句：\n________，恨别鸟惊心。',
  '感时花溅泪。',
  '结合“感时”“恨别”理解诗人的忧国思家之情。',
  { variant: 'poem-previous' },
);
add(
  'core-chinese-3',
  1,
  '补全随机挖空：\n国破____在，城春____深。',
  '山河；草木。',
  '“国破”与“山河在”形成反差，城中草木丛生反衬人事凋零。',
  { variant: 'poem-cloze' },
);
add(
  'core-chinese-3',
  3,
  '《春望》的作者是谁？写于哪一朝代？',
  '杜甫；唐代。',
  '杜甫在安史之乱期间身陷长安，诗中寄寓忧国思家之情。',
);
add(
  'core-chinese-4',
  1,
  '“学而时习之，不亦说乎？”中的“说”是什么意思？',
  '“说”同“悦”，愉快。',
  '这是通假用法，应结合语境理解。',
);
add(
  'core-chinese-5',
  2,
  '阅读：\n“走廊尽头的灯忽明忽暗。她握紧信封，听见门后传来一声轻响。”\n结合原文，分析环境描写的作用。',
  '昏暗闪烁的灯光与门后的轻响营造紧张、神秘的氛围；与人物握紧信封的动作呼应，烘托其不安，激发读者对后续情节的期待。',
  '作用分析需先引用细节，再解释效果。',
  {
    type: 'subjective',
    passage: '走廊尽头的灯忽明忽暗。她握紧信封，听见门后传来一声轻响。',
    rubric: [
      {
        id: 'detail',
        title: '文本细节',
        max: 2,
        description: '引用灯光、轻响等具体细节。',
        skillId: 'skill-2',
      },
      {
        id: 'effect',
        title: '表达效果',
        max: 2,
        description: '分析紧张氛围、人物不安或悬念，并说明联系。',
        skillId: 'skill-2',
      },
    ],
  },
);
add(
  'core-math-1',
  2,
  '解方程：3(x − 2) = 2x + 5。',
  'x = 11',
  '把解代回两边：3×9 = 22+5 = 27。',
  {
    difficulty: 1,
    solution: [
      '已知 3(x−2)=2x+5。',
      '用等式性质，先去括号。',
      '3x−6=2x+5。',
      '移项得 x=11。',
      '检验：左右两边均为27，因此 x=11。',
    ],
  },
);
add(
  'core-math-2',
  3,
  '求二次函数 y = 2x² − 4x − 6 的顶点坐标。',
  '(1, −8)',
  '配方得到 y = 2(x − 1)² − 8。',
  {
    solution: [
      '已知 a=2，b=−4，c=−6。',
      '选择配方法或顶点公式。',
      'y=2(x²−2x)−6=2[(x−1)²−1]−6。',
      '化简为 y=2(x−1)²−8。',
      '顶点坐标为 (1,−8)。',
    ],
    diagram: {
      type: 'function_graph',
      functions: [{ expression: '2*x^2-4*x-6', label: 'y = 2x² − 4x − 6' }],
      xRange: [-3, 5],
      yRange: [-10, 12],
      showAxes: true,
      showGrid: true,
    },
  },
);
add(
  'core-math-2',
  4,
  '已知 y = (x − 3)² + 2，求函数的最小值，以及取得最小值时的 x。',
  '最小值为 2，在 x = 3 时取得。',
  '平方数不小于0。',
  {
    variant: 'minimum',
    solution: [
      '函数已写成顶点式。',
      '使用平方非负的性质。',
      '(x−3)²≥0。',
      '当 x=3 时，平方项为0。',
      '故最小值为2，且此时 x=3。',
    ],
  },
);
add(
  'core-math-2',
  2,
  '抛物线 y = −(x + 2)² + 4 的开口方向和对称轴分别是什么？',
  '开口向下；对称轴为 x = −2。',
  '二次项系数为负；顶点横坐标为−2。',
);
add(
  'core-math-3',
  2,
  '直角三角形的两条直角边分别是 6 cm 和 8 cm，求斜边长。',
  '10 cm',
  '6²+8²=36+64=100，斜边长为√100=10 cm。',
  {
    solution: [
      '两直角边长为6 cm、8 cm。',
      '选择勾股定理。',
      'c²=6²+8²。',
      'c²=100，c为正数。',
      '斜边长为10 cm。',
    ],
    diagram: {
      type: 'geometry',
      canvas: { width: 500, height: 300 },
      points: [
        { id: 'A', x: 100, y: 240 },
        { id: 'B', x: 400, y: 240 },
        { id: 'C', x: 100, y: 60 },
      ],
      segments: [
        ['A', 'B'],
        ['B', 'C'],
        ['C', 'A'],
      ],
      labels: true,
      labelsText: [
        { x: 240, y: 270, text: '8 cm' },
        { x: 45, y: 155, text: '6 cm' },
      ],
    },
  },
);
add(
  'core-math-5',
  2,
  '数据 2、3、3、7、10 的平均数和中位数分别是多少？',
  '平均数为5；中位数为3。',
  '总和25，除以5得5；排好序后中间的第三个数为3。',
  { variant: 'data-analysis' },
);
add(
  'core-english-1',
  2,
  '“The door handle turned slowly. Maya held her breath, unsure who was on the other side.”\nWhich details create suspense?',
  'The slowly turning handle delays the reveal, and Maya’s uncertainty creates anticipation and possible threat.',
  'Identify the specific detail, the technique, and its effect on the reader.',
);
add(
  'core-english-2',
  3,
  'How is foreshadowing different from a flashback?',
  'Foreshadowing hints at a future event; a flashback presents an event from the past.',
  'The difference concerns the direction in narrative time, not merely whether information is revealed.',
);
add(
  'core-english-7',
  3,
  'Write an analytical paragraph about how this passage creates suspense.\n\n“The key was missing. Upstairs, a floorboard creaked. Noah had locked the house from the inside.”',
  'A strong response argues that unexplained details create uncertainty, cites the missing key and the creaking floorboard, and explains how the locked house makes an intruder seem impossible yet threatening.',
  'Link each quotation to a specific inference. Avoid simply retelling the passage.',
  {
    type: 'subjective',
    passage:
      'The key was missing. Upstairs, a floorboard creaked. Noah had locked the house from the inside.',
    expectedSeconds: 240,
    rubric: [
      'Thesis',
      'Evidence',
      'Analysis',
      'Organization',
      'Clarity',
      'Language',
      'Grammar',
    ].map((title, i) => ({
      id: title.toLowerCase(),
      title,
      max: i === 2 ? 4 : 2,
      description: `Evaluate ${title.toLowerCase()} in relation to the passage and analytical task.`,
      skillId: 'skill-' + (i + 1),
    })),
  },
);
const ceExamples: [number, string, string[], string, string][] = [
  [
    1,
    'The collection of rare manuscripts ___ stored in a climate-controlled room.',
    ['A. are', 'B. is', 'C. were', 'D. have been'],
    'B. is',
    'The singular subject “collection” takes the singular verb “is”.',
  ],
  [
    2,
    'By the time the lecture began, Maya ___ all the assigned chapters.',
    ['A. reads', 'B. has read', 'C. had read', 'D. will read'],
    'C. had read',
    'The reading was completed before another past event.',
  ],
  [
    3,
    'The teacher handed the papers to Leo and ___.',
    ['A. I', 'B. me', 'C. my', 'D. mine'],
    'B. me',
    '“Me” is the object of the preposition “to”.',
  ],
  [
    4,
    'Choose the sentence with a correctly placed modifier.',
    [
      'A. Walking to school, the rain soaked Mia.',
      'B. Walking to school, Mia was soaked by the rain.',
      'C. Walking to school, Mia’s umbrella broke.',
      'D. Walking to school, the streets were wet.',
    ],
    'B. Walking to school, Mia was soaked by the rain.',
    'Mia, the grammatical subject, is the person walking.',
  ],
  [
    5,
    'The workshop teaches students to research, to draft, and ___.',
    ['A. revising', 'B. revision', 'C. to revise', 'D. revised'],
    'C. to revise',
    'The three infinitive phrases use parallel grammatical structure.',
  ],
  [
    6,
    'The evidence was limited___ the researchers avoided a firm conclusion.',
    ['A. ,', 'B. ;', 'C. because', 'D. although'],
    'B. ;',
    'A semicolon can join these two independent clauses.',
  ],
  [
    7,
    'Choose the correctly punctuated sentence.',
    [
      'A. The trial ended, the results were published.',
      'B. The trial ended; the results were published.',
      'C. The trial ended the results were published.',
      'D. The trial ended, published the results.',
    ],
    'B. The trial ended; the results were published.',
    'A semicolon correctly separates the two independent clauses.',
  ],
  [
    8,
    'Which choice is a dependent clause?',
    [
      'A. The sun rose.',
      'B. They left early.',
      'C. Because the road was closed',
      'D. We chose another route.',
    ],
    'C. Because the road was closed',
    '“Because” makes the clause depend on a main clause.',
  ],
  [
    9,
    'The first design was inexpensive. ___, it failed every durability test.',
    ['A. Similarly', 'B. For example', 'C. However', 'D. Therefore'],
    'C. However',
    'The second sentence contrasts low cost with poor durability.',
  ],
  [
    10,
    'The researcher was ___ about the claim because no evidence supported it.',
    ['A. skeptical', 'B. certain', 'C. indifferent', 'D. enthusiastic'],
    'A. skeptical',
    'Lack of supporting evidence explains doubt.',
  ],
];
for (const [i, prompt, options, answer, explanation] of ceExamples)
  add(`core-ce-${i}`, 2, prompt, answer, explanation, {
    type: 'choice',
    options,
    variant: 'grammar-context',
    tags: ['Grammar', '原创练习，非官方试题'],
  });
add(
  'core-physics-1',
  2,
  '一辆小车在 10 s 内匀速行驶 60 m，求速度，分别用 m/s 和 km/h 表示。',
  '6 m/s；21.6 km/h',
  'v=s/t=60/10=6 m/s；乘3.6得21.6 km/h。',
);
add(
  'core-physics-4',
  1,
  '一束光与镜面的夹角为 30°，反射角是多少？',
  '60°',
  '入射角相对于法线测量，因此为90°−30°=60°。反射角等于入射角。',
  {
    diagram: {
      type: 'physics',
      canvas: { width: 500, height: 300 },
      points: [
        { id: 'L', x: 50, y: 240 },
        { id: 'R', x: 450, y: 240 },
        { id: 'O', x: 250, y: 240 },
        { id: 'N', x: 250, y: 40 },
      ],
      segments: [
        ['L', 'R'],
        ['O', 'N'],
      ],
      arrows: [{ x1: 65, y1: 130, x2: 250, y2: 240, label: '入射光' }],
      labelsText: [
        { x: 268, y: 60, text: '法线' },
        { x: 345, y: 265, text: '平面镜' },
      ],
    },
  },
);
add(
  'core-physics-6',
  2,
  '一块金属质量为 54 g，体积为 20 cm³，求密度。',
  '2.7 g/cm³，即 2700 kg/m³',
  'ρ=m/V=54/20=2.7 g/cm³。',
);
add(
  'core-physics-9',
  2,
  '物体对水平面的压力为 100 N，接触面积为 0.02 m²，求压强。',
  '5000 Pa',
  'p=F/S=100/0.02=5000 Pa。',
);
add(
  'core-physics-10',
  2,
  '物体浸没水中，排开水的体积为 0.002 m³，取 g=10 N/kg，求浮力。',
  '20 N',
  'F浮=ρ水gV排=1000×10×0.002=20 N。',
);
add(
  'core-physics-11',
  2,
  '工人用 50 N 的水平拉力，使箱子沿水平方向移动 4 m，用时 10 s。求拉力做的功和功率。',
  '功为200 J，功率为20 W。',
  'W=Fs=50×4=200 J；P=W/t=200/10=20 W。',
);
add(
  'core-chemistry-5',
  2,
  '氧化铝中铝元素为 +3 价，氧元素为 −2 价，写出化学式。',
  'Al₂O₃',
  '2×(+3)+3×(−2)=0。',
);
add(
  'core-chemistry-6',
  2,
  '配平：\n__ Fe + __ O₂ → __ Fe₃O₄',
  '3 Fe + 2 O₂ → Fe₃O₄',
  '铁原子：3=3；氧原子：4=4。反应条件为点燃。',
);
add(
  'core-chemistry-6',
  1,
  '写出氢气在氧气中燃烧的化学方程式，并注明条件。',
  '2 H₂ + O₂ → 2 H₂O（点燃）',
  '氢、氧原子数分别守恒；化学式下标不能为了配平而改变。',
);
add(
  'core-chemistry-8',
  2,
  '向澄清石灰水中通入少量二氧化碳，观察到什么现象？',
  '澄清石灰水变浑浊。',
  'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O，生成难溶的碳酸钙。',
);
add(
  'core-history-1',
  4,
  '从生产方式和社会生活两个角度，分析工业革命的影响。',
  '生产方式：机器生产逐步代替手工劳动，提高生产力，促进工厂制度。社会生活：推动城市化，也带来劳工问题、贫富差距和环境污染。',
  '分析应涵盖积极与消极影响，并从具体角度展开。',
  {
    type: 'subjective',
    rubric: [
      {
        id: 'production',
        title: '生产方式',
        max: 3,
        description: '机器、工厂制度与生产力的联系。',
        skillId: 'skill-4',
      },
      {
        id: 'social',
        title: '社会生活',
        max: 3,
        description: '城市化及社会或环境问题，分析有具体内容。',
        skillId: 'skill-4',
      },
    ],
  },
);
export const corePack: Pack = {
  schemaVersion: 1,
  manifest: {
    id: 'review-core',
    title: '多学科基础学习包',
    version: '1.0.0',
    subject: 'all',
    description:
      '覆盖八科学科框架的原创基础示例。适合初次诊断，可配合自己的课程资料扩展。',
    changelog: '首次发布：知识框架、基础练习、阅读与写作评分标准。',
    compatibility: 'Review 1.x',
  },
  knowledge: seedNodes,
  questions: seedQuestions,
  keyterms: seedNodes.filter((n) => n.subject === 'english'),
  rubrics: seedQuestions.flatMap((q) => q.rubric ?? []),
};
export const reactions = [
  {
    id: 'carbon',
    from: 'C',
    to: 'CO₂',
    reactants: 'C + O₂',
    products: 'CO₂',
    condition: '点燃，氧气充足',
    equation: 'C + O₂ → CO₂',
    phenomenon: '碳燃烧，放出热量。',
    nodeId: 'core-chemistry-8',
  },
  {
    id: 'lime',
    from: 'CO₂',
    to: 'CaCO₃',
    reactants: 'CO₂ + Ca(OH)₂',
    products: 'CaCO₃↓ + H₂O',
    condition: '通入澄清石灰水',
    equation: 'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',
    phenomenon: '澄清石灰水变浑浊。',
    nodeId: 'core-chemistry-8',
  },
  {
    id: 'hydrogen',
    from: 'H₂',
    to: 'H₂O',
    reactants: '2 H₂ + O₂',
    products: '2 H₂O',
    condition: '点燃',
    equation: '2 H₂ + O₂ → 2 H₂O',
    phenomenon: '产生淡蓝色火焰，放热。',
    nodeId: 'core-chemistry-6',
  },
  {
    id: 'water',
    from: 'H₂O',
    to: 'H₂',
    reactants: '2 H₂O',
    products: '2 H₂↑ + O₂↑',
    condition: '通电',
    equation: '2 H₂O → 2 H₂↑ + O₂↑',
    phenomenon: '两极产生气泡，负极和正极气体体积比约2:1。',
    nodeId: 'core-chemistry-4',
  },
];
